# Site settings
title: "Dave McDowell | Designer & Developer"
name: Dave McDowell
email: davecmcdowell@gmail.com
description: >-
  The portfolio of Dave McDowell, you've arrived.
baseurl: "/portfolio"
url: "https://www.dcmcdowell.com"

twitter_username: "@func_dave"
github_username:  davemcdowell 

#custom defines
mailto_url: mailto:dave@dcmcdowell.com
github_url: https://github.com/davemcdowell
steam_url: https://steamcommunity.com/id/cptyossarian/
linkedin_url: https://www.linkedin.com/in/davecmcdowell/
twitter_url: https://twitter.com/func_dave
# end customs

author:
  name: Dave McDowell
  twitter: "@func_dave"
  image: "..."
twitter:
  username: "@func_dave"
  card: summary_large_image
social:
  name: Dave McDowell
  links:
    - https://twitter.com/func_dave
    - https://steamcommunity.com/id/cptyossarian/
    - https://www.linkedin.com/in/davecmcdowell/
    - https://github.com/davemcdowell

google_analytics: "G-FW1FS38ZN7"

# timezone
timezone: America/Los_Angeles

# paginate: defines
paginate: 5
paginate_path: "/blog/page:num/"

# last-modified-at: defines
last-modified-at:
    date-format: '%d-%b-%y'

# Build settings
#theme: moxxi
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
 #exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
