# Site settings
title: Dave McDowell | Designer + Developer
name: Dave McDowell
email: davecmcdowell@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/portfolio"
url: "https://www.dcmcdowell.com"
twitter_username: "@func_dave"
github_username:  davecmcdowell
mailto_url: mailto:dave@dcmcdowell.com
github_url: https://github.com/davemcdowell
steam_url: https://steamcommunity.com/id/cptyossarian/
linkedin_url: https://www.linkedin.com/in/davecmcdowell/
twitter_url: https://twitter.com/func_dave

# Build settings
#theme: moxxi
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
 #exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
