<<<<<<< HEAD
# Site settings
title: Dave McDowell | Designer + Developer
email: dcmcdowell@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.dcmcdowell.com"
twitter_username: @func_dave
github_username:  jekyll

# Build settings
#theme: moxxi
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
=======
# basic options
title: Dave McDowell | Portfolio
author: Dave McDowell
email: davecmcdowell@gmail.com
description: The portfolio of Dave McDowell - Designer and Developer based in Seattle
#twitter_username: 
#github_username:


# build settings
markdown: kramdown
theme: minima
>>>>>>> fc31e758afc0e9e414a9179b77efca3b7ed81d17
